services:
  # Frontend React application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - transcription-network

  # Backend FastAPI service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/src/recordings:/app/recordings
    environment:
      - REDIS_URL=redis://localhost:6379/0
    networks:
      - transcription-network

  # Celery worker for processing tasks
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    volumes:
      - ./backend:/app
      - ./backend/src/recordings:/app/recordings
    depends_on:
      - backend
    environment:
      - REDIS_URL=redis://localhost:6379/0
      - PYTHONPATH=/app
    working_dir: /app
    networks:
      - transcription-network
    command: celery -A src.celery_app worker --loglevel=info

networks:
  transcription-network:
    driver: bridge

volumes:
  redis-data:
